### ISSUE TITLE
Where are the data saved?

### ISSUE THREAD

**Issue by biapar** [kjac/FormEditor#100]
Where are the data saved?

**Comment by kjac** [comment]
Hey @biapar,

If you're using the default storage (read: if you haven't explicitly changed it), the data is stored in Lucene indexes per Umbraco node in `~/App_Data/FormEditor/[node ID]`.

Check [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/storage.md) for more info ´.

**Comment by kjac** [comment]
Closing this now... @biapar feel free to reopen if you have any further questions.

**Comment by biapar** [comment]
Why Do you save the data into Lucene indexes?

**Comment by kjac** [comment]
@biapar because they support a wide range of advanced features that are hard to replicate with SQL - statistics among other things.

However, as you can read in [the documentation](https://github.com/kjac/FormEditor/blob/master/Docs/storage.md) you can swap the storage index, and there are samples available for storage indexes based on SQL and Elastic.
