### ISSUE TITLE
Object reference not set to an instance of an object in NoScript.cshtml

### ISSUE THREAD

**Issue by shakibmiraki** [kjac/FormEditor#104]
i created a form in my Home Document Type and put it in my layout page to render in every pages,
it works well on the home page but give me the "Object reference not set to an instance of an object" error in NoScript.cshtml
is this my wrong or an issue ?

**Comment by kjac** [comment]
Hey. Could you please attach a screen shot so I can see what's causing the
null reference exception?

My first thought is that you may have named your form property something
else than "form". But try attaching a screen shot and I'll look at it as
soon as I'm able.

**Comment by shakibmiraki** [comment]
no i name it form, but this is the error on every page except home page that i created the form in this document type.
![capture](https://cloud.githubusercontent.com/assets/15976357/21348484/a1917aea-c6c2-11e6-93d1-9a5113fa658e.PNG)
![object reference not set to an instance of an object](https://cloud.githubusercontent.com/assets/15976357/21348483/a190c7c6-c6c2-11e6-9c89-3f33a40cbad8.png)

**Comment by kjac** [comment]
Hi again. Thanks. I'll have a look in a couple of hours, looks like it's
easily fixable.

**Comment by kjac** [comment]
Hi @shakibmiraki,

It looks like Umbraco isn't initializing a `FormModel` instance when there's no form defined on the document type or content (e.g. on the child pages to your home page).

Could you please try changing [line 11](https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/Views/Partials/FormEditor/NoScript.cshtml#L11) in `/Views/Partials/FormEditor/NoScript.cshtml` to this: 

`var form = formContent.GetPropertyValue<FormModel>(formPropertyName) ?? new FormModel();`

If that works I'll update the default views to handle this situation more gracefully.

**Comment by shakibmiraki** [comment]
Hi @kjac 
after changing this line i get another error.
![object reference not set to an instance of an object](https://cloud.githubusercontent.com/assets/15976357/21364624/ddb055ac-c706-11e6-9f68-6da5b07d183d.png)

**Comment by kjac** [comment]
@shakibmiraki excellent. At least I know where the problem lies then.

I think this is caused because you're calling the Form Editor partial (`NoScript.cshtml`) while rendering a page that does not contain a Form Editor property. You mentioned that you're calling it on every page, but that the Form Editor property is only on your Home page? You shouldn't call it unless you have a Form Editor property to render.

If you're trying to render the Form Editor property from your Home page on every page, you should take a look at [this documentation](https://github.com/kjac/FormEditor/blob/master/Docs/reuse.md) or [this tutorial](https://github.com/kjac/FormEditor/blob/master/Tutorials/HelloFormEditor.md).

In any case I will update the default views to counter for this problem in the next release, so the site doesn't crash.

**Comment by shakibmiraki** [comment]
yes @kjac  that works for me.
my fault.
thanks you.

**Comment by kjac** [comment]
@shakibmiraki glad to hear that... and thank you for bringing the issue to my attention. I'll make sure the bundled views take this situation into account in the next (imminent) release.
