### ISSUE TITLE
Update from 0.13.2.1 to 0.17.1.1 and now our data is "gone" 

### ISSUE THREAD

**Issue by GameMonkey** [kjac/FormEditor#114]
So ive just updated this solution, and now my data entries are "gone", but think they are just not being displayed. 

If i dig into the api controller it also just returns null as values, any idea why or how to fix it? This is not put into production yet still on the stage server.

We are running the SQL implementation (Yeah i know, we are not doing this on the newer solutions)

![screenshot_21](https://cloud.githubusercontent.com/assets/7374161/23305267/4023616e-fa9e-11e6-8972-0ad19f0b9d7c.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/7374161/23305268/402815ba-fa9e-11e6-8a0e-af05f47d642f.png)

**Comment by rasmusfjord** [comment]
Ups wrong account i posted from, this is my issue not GameMonkey :) GameMonkey is a friend.

**Comment by kjac** [comment]
@rasmusfjord Strange. I can't exactly put my finger on the problem. Off the top of my head I'm thinking...

1. Did you rebuild the SQL index with the corresponding version of FormEditor.Binaries (0.17.1.1)?
2. Are there any messages in the Umbraco log that might bring some clarity?

It none of the above lead you anywhere, try attaching a debugger to [this line](https://github.com/kjac/FormEditor/blob/master/Samples/SQL%20storage%20index/Storage/Index.cs#L82) and see `GetPage()` yields any results from the DB.

**Comment by rasmusfjord** [comment]
Hey @kjac 

I forgot about the sql index dll so i quickly rebuilded it against the new version, but it didnt change anything, check logs, nothing here, so i did a custom build just with a logger on the "Get" method you talked about and the data is good.

   LogHelper.Info<Index>(JsonConvert.SerializeObject(rows));
		

This is the data for the form and its all there just not being displayed.
https://gist.github.com/rasmusfjord/2aedf043ce80a77a44e6a1f1450e6bf7

here is the form, and there are no console errors in the browser, and there is no data api call on the fields. 

But something ive noticed changed since v.13 to v. 17 is the _sortName field is the one being used to call out the alias of the field, we have some minor stuff using the field besides the form it self so had to change it there, could it be something like that?

**Comment by kjac** [comment]
@rasmusfjord might be. Or it might be something with an underscore prefix that was introduced a while back, but possibly never tested properly with the SQL index in an upgrade scenario.

I'll try to reproduce it as soon as I can.

**Comment by kjac** [comment]
@rasmusfjord It's the underscore issue 😞 

I've got at fix for it, but it'll be a day or two before I can test it thoroughly - then I'll release a new version.

**Comment by rasmusfjord** [comment]
@kjac you are the man Kenn!

**Comment by kjac** [comment]
@rasmusfjord the issue is fixed in the next release, but GitHub is being childish at the moment, so I can't publish the release just now... hopefully soon.

**Comment by kjac** [comment]
@rasmusfjord There. Finally. It's released 😄 thanks for the issue report 👍

**Comment by rasmusfjord** [comment]
@kjac Wow thank you Kenn for reacting so fast!

**Comment by rasmusfjord** [comment]
and now it works again :)

**Comment by kjac** [comment]
Awesome!
