### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by bobi33** [kjac/FormEditor#128]
Hi again, I think I may not fully grasp the email notifications. I've added a sender and recipient email address to the notification section of the form content type in the back end (ie. when the form is submitted an email is sent to an email address). However, emails aren't sending when the form is submitted. I'm wondering whether I missed something (I've just added the email address that the notification should get sent to in the back end).

**Comment by kjac** [comment]
Hi @bobi33,

Did you configure the `<mailSettings/>` in web.config correctly?

Also, try checking the log files (\App_Data\Logs) for any clues as to what might be going on.

**Comment by bobi33** [comment]
Hi @kjac,

Yup. I'm using a simple gmail email address to make things simple.

I'll outline what I've done, in case I am missing something:

Yup, 
1. I configured the mailSettings in web.config:

>      <mailSettings>
>       <smtp from="email@gmail.com">
>         <network host="smtp.gmail.com" userName="email@gmail.com" password="myOutstandingPassword" port="465" />
>       </smtp>
>     </mailSettings>

2. I configured the form "Emails" tab to have a notification email:

I included the same recipient email address as the sender's email address - as the above-noted address in mailSettings, email@gmail.com.

Perhaps I missed something.

**Comment by kjac** [comment]
Hi @bobi33,

That looks fine, if Google indeed does support it. In the past I recall having trouble using the same gmail address as sender AND recipient.

The best way to test if the emails are indeed being sent by Form Editor is to write the outgoing emails to a folder on your disk instead of sending them to an SMTP server. Check [this article](https://msdn.microsoft.com/en-us/library/ms164241(v=vs.110).aspx) on MSDN.

**Comment by kjac** [comment]
@bobi33 closing this now. Hope you got it working.
