### ISSUE TITLE
Problem with dropdown values if they contains a comma (,)

### ISSUE THREAD

**Issue by rpjengaard** [kjac/FormEditor#133]
Hi Kenn,

first of all thanks for this great package :-). 

I have found a bug regarding dropdown-lists (or maybe all values containing comma?). If i create a value in a dropdown-list containing a comma (,), i can not submit the form. I get this in return

`{"invalidFields":[{"name":"Rulleboks","formSafeName":"_Rulleboks","submittedValue":"Lyd og, collage – din nye ven","invalid":true}],"failedValidations":[]}`

I´m running v1 on Umbraco 7.5.4.

Could you take a look at this?

Best regards
René

**Comment by kjac** [comment]
Hey @rpjengaard,

Looks like the submitted value with the comma isn't properly encoded. I'll see what can be done about it.

Thanks for reporting this!

**Comment by kjac** [comment]
So I dug into this, and it's not encoding. The problem is that all the multi value fields share the same code, whether they allow multiple values selected or not. And multiple values are the culprit here, because they're submitted as comma separated lists of values. So when one of the values contains a comma... you guessed it; the parsing on the server side goes haywire.

I'm going to ponder this for a bit. If I can't solve it without rewriting a whole bunch of code, I'll have to simply disallow field values with commas on all multi value fields. 

Thoughts?

**Comment by rasmusfjord** [comment]
Hey Kenn

Did you do anything to this so that its not possible or other solution? Just if its worth an update for a customer of ours, or if its still there :) And merry Christmaes.

**Comment by kjac** [comment]
Hi @rasmusfjord ,

I ended up stripping commas from multi value field values; see [this line](https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/Plugin/js/directives/multiSelectValue.js#L17). It's probably worth digging into an upgrade for your customer :)

And merry Christmas to you too!

**Comment by rasmusfjord** [comment]
thanks man for the update and for building an awesome product :)

**Comment by kjac** [comment]
You're so very welcome!

Den 18. dec. 2017 8.55 AM skrev "rasmusfjord" <notifications@github.com>:
