### ISSUE TITLE
Feature Request: Signature Field

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#141]
I would like to have an signature field that saves the signature that the user "draws" as an image.
I am thinking of implementing this using [Signature_Pad](https://github.com/szimek/signature_pad/) and am interested if this is a feature that would be useful in the base product or if you have thought about an area for optional fields

**Comment by kjac** [comment]
Hi @BarryGibson,

That's pretty cool. I'm sure it'd be a useful field for others. However I can't really add it to the core since it has an external script dependency. 

At the moment I'm not going to start up a new GitHub project for 3rd party field types. I simply haven't got the time to maintain it.

Thanks for offering though, it's really awesome of you.

**Comment by kjac** [comment]
I've found no time to start a side project for custom fields and other extensions. If anyone's up for the task, by all means do so. 

I'm closing this for the time being.
