### ISSUE TITLE
Email reply-to and name

### ISSUE THREAD

**Issue by thomassen88** [kjac/FormEditor#169]
Hi Kjac,
I have a question about the email Confirmation and Notification emails.
Is it possible to set an reply-to address and a custom sender-name?

**Reply to:**
One our clients are using an subdomain for their transaction-emails and want to set their contact-email as an "reply to"-address.

Example: 
from: transaction@sub.example.com
reply to: contact@example.com

**Custom sender-name:**
The sender name is automaticly set to the name from the left part of the email-address (**transaction**@...)
Is it possible to change it to ex: Example corp?

**Comment by thomassen88** [comment]
One more thing:
Is it possible to change the date format to: dd.mm.yyyy on the date-field in the email-template?

**Comment by kjac** [comment]
Hi @thomassen88,

I can't figure out if you solved your first question since you closed the issue; but there's no way to configure reply-to addresses in the UI. Out of the box it will always be the same as the sender address. However, if you really want to change it (and you're into C#), you can hook into the `BeforeSendMail` event on `FormModel` and manipulate the `MailMessage` object ([see the docs](https://github.com/kjac/FormEditor/blob/master/Docs/extend.md#email-sending-events)). I'd strongly advise against changing the reply-to address, though. You risk confusing the users, or even worse - they might suspect the email being a fraud.

As for your second question... the email template is your own implementation, so you should be able to render the field data in any way you'd like. Check [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/emails.md) for more info 😄

**Comment by kjac** [comment]
I'm closing this issue now due to lack of feedback. Feel free to reopen it if you still need help with it.
