### ISSUE TITLE
SQL Storage

### ISSUE THREAD

**Issue by viral-1** [kjac/FormEditor#170]
Have the latest version of FormEditor 1.3.1.1 with Umbraco 7.7.6 and we are wanting to move the storage to the SQL Server that is hosting Umbraco data.  According to your instructions we just add &lt; Index type="FormEditor.SqlIndex.Storage.Index, FormEditor.SqlIndex" /&gt; to the FormEditor.config file.  

This is not working... is anything else required to make this work?  We have removed the files under TEMP and Cache restarted the server, edited the Web.config file. 
Any help with this is greatly appreciated!

**Comment by kjac** [comment]
Hi @viral-1,

The [documentation](https://github.com/kjac/FormEditor/blob/master/Docs/storage.md#changing-the-storage-index) might not be entirely clear on this subject... but the SQL index mentioned in the docs is the one from the [samples section](https://github.com/kjac/FormEditor/tree/master/Samples/SQL%20storage%20index). 

In order to use it, you'll need to pull a copy of the samples solution and build it yourself. It's not part of the FormEditor core.

**Comment by kjac** [comment]
I'm closing this issue now due to lack of feedback. Feel free to reopen it if you still need help with it.
