### ISSUE TITLE
Feature reques.

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#76]
Hi guess who brakes again :)
 how much time it would take to make all custom properties using the rewrite function like the body that you can insert {{propertyName}} to get its value.

Confirmation email -> Email subject
Notification email -> Email subject
Receipt -> heading
Receipt -> text

Wit this it would be possible to make more personalized responses and notifications.

An practical example.
a contact from post with subject "Contact from" could be changed to "Contact from from {{Name}} {{Surrname}}" => "Contact form from John Do", afterward it is supper easy to find it in the mailbox. 

Name and Surrname are form fiedls.

**Comment by kjac** [comment]
@eriksimonic Good idea 👍 - and it shouldn't take too long to add. I'll include this in the next version... won't be long until I'm ready to release it.

**Comment by eriksimonic** [comment]
@kjac Yes as I am migrating from an SharePoint site we had a FormEditor very similar to this one. 
And that was really great feature. 

BTW.
It is possible to create a custom field with a content picker?
I would like to create a check box TOS/TOC agreement control..

**Comment by eriksimonic** [comment]
@kjac 

Another question regarding body of the email.
It would make sense to include basic formatting in the email body. So the editor can ascent some text or add links to it.. / Maybe MarkDown or simple html editor..  what do you think. 
If it is not mainstream I will handle it in the template with a markdown processor. 

Regards.

**Comment by kjac** [comment]
@eriksimonic to address your last comment first: Since emails aren't necessarily HTML formatted, it won't make much sense to encourage the users to use markup in the body text. If you can solve your requirement in the template, that's cool :) 

With regards to the content picker in a custom field. it should be quite possible to do - you can have a look at the [Link field type](https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/Plugin/editor/fields/core.link.html) for inspiration. 

However, if the TOS page is general/multipurpose and used other places on the site, I would go with another approach. I wouldn't give the editors a chance to pick the wrong page - I would handle it myself in the field's partial view. Remember you have full access to the Umbraco helper in the partial view. Anyway... just food for thought.

**Comment by eriksimonic** [comment]
@kjac 
Agree, I had in mind for a such control IE checkbox with a link to terms and conditions page, what a editor select it is really not may domain. as editors have to change those agreements based on the submission type, just a specific requirement.  I will check the new feature to se if everything works as expected. !

Regards.

**Comment by kjac** [comment]
@eriksimonic thanks again for the feature suggestion 👍
