### ISSUE TITLE
Feature request : Conditions

### ISSUE THREAD

**Issue by tonag** [kjac/FormEditor#8]
Hello, is there in plan to add Conditions so it is possible to build a survey or more complex forms ?
Thank you.

**Comment by kjac** [comment]
Hi @tonag. I've considered it several times, but I have yet to work out a way to make conditions simple to work with from an editor perspective. 

Until now, the best solution I can come up with is to extend or reshape the validation system into a condition system. This could be used in broader terms to support conditions of multiple types, including validation, show/hide fields etc. But the prototypes I've built have so far turned out to be an editorial nightmare.

Any ideas, wireframes, sketches, drawings on napkins etc. would be welcome :)

**Comment by rocifier** [comment]
What about something like how azure logic apps does conditions?

**Comment by kjac** [comment]
Implemented with #106 😄
